name: CI

on:
  push:
    branches: ["main", "*"]
  pull_request:

jobs:
  lint-test-docs:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ matrix.python-version }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff Lint
        run: ruff . --select=E,F,I
      - name: Black Check
        run: black --check .
      - name: Pytest with nbmake
        run: pytest --nbmake -p no:warnings
      - name: Build Jupyter Book
        run: jupyter-book build docs
      - name: Progress Badge
        run: |
          python scripts/progress.py
          mkdir -p docs/_build/html/badges
          cp badges/progress.json docs/_build/html/badges/progress.json
      - name: Upload Book Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: docs/_build/html

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: lint-test-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: site
          path: site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
